### ISSUE TITLE
Getting this warning "Cannot access 'androidx.lifecycle.FullLifecycleObserver' which is a supertype of 'com.skydoves.powerspinner.PowerSpinnerView'. Check your module classpath for missing or conflicting dependencies" 

### ISSUE THREAD

**Issue by AzizFasihHazel** [skydoves/PowerSpinner#159]
Getting this warning "Cannot access 'androidx.lifecycle.FullLifecycleObserver' which is a supertype of 'com.skydoves.powerspinner.PowerSpinnerView'. Check your module classpath for missing or conflicting dependencies" because of this am not able to get release apk. Both the dependencies powerspinner and powermenu are latest 1.2.6 and 2.2.3.

It was working fine before, today I get these error and after that i update it to latest version but still getting the warnings.

**Comment by skydoves** [comment]
@AzizFasihHazel  Would you add the dependency below to your project?

```gradle
implementation("androidx.lifecycle:lifecycle-common-java8:2.6.1")

```

**Comment by skydoves** [comment]
@AzizFasihHazel A new version 1.2.7 has been released. if you still face the same issue, you should use lifecycle version at least 2.6.0 by force. Thanks for reporting this issue!

**Comment by AzizFasihHazel** [comment]
am still getting the same issue with updated version also. Libraries are : 
 ///viewModel && lifecycle
    implementation "androidx.lifecycle:lifecycle-extensions:2.2.0"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.6.1"

 /// custom spinner
    implementation "com.github.skydoves:powerspinner:1.2.7"
    implementation "com.github.skydoves:powermenu:2.2.3"

**Comment by skydoves** [comment]
`lifecycle-extensions` dependency has been already deprecated. You should remove all outdated lifecycle dependencies, including your androidx.appcompat and androidx.material.

**Comment by skydoves** [comment]
This issue happened because you're using duplicated old and new versions of lifecycle libraries and their compiled code can't exist in the same project.

**Comment by AzizFasihHazel** [comment]
Hy Jaweoong Enum, am getting this crash on my live app that belongs to this
dependency Caused by java.lang.reflect.InvocationTargetException:
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:876)
       at
android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1064)
       at
android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1019)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1181)
       at
android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1142)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1184)
       at
android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1142)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1184)
       at
android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1142)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:701)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:553)
       at
com.example.step.databinding.FragmentReportBinding.inflate(FragmentReportBinding.java:70)
       at
com.example.step.ui.report.ReportFragment.onCreateView(ReportFragment.kt:39)
       at
androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114)
       at
androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
       at
androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
       at
androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
       at
androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
       at
androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1751)
       at
androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:317)
       at
androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(FragmentStateAdapter.java:341)
       at
androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:276)
       at
androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:67)
       at
androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:7867)
       at
androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:893)
       at
androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:107)
       at
androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8902)
       at
androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8860)
       at
androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8848)
       at
androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1645)
       at
androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
       at
androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
       at
androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
       at
androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
       at
androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
       at android.view.View.layout(View.java:23475)
       at android.view.ViewGroup.layout(ViewGroup.java:6526)
       at
androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:527)
       at android.view.View.layout(View.java:23475)
       at android.view.ViewGroup.layout(ViewGroup.java:6526)
       at
androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
       at android.view.View.layout(View.java:23475)
       at android.view.ViewGroup.layout(ViewGroup.java:6526)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23475)
       at android.view.ViewGroup.layout(ViewGroup.java:6526)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:23475)
       at android.view.ViewGroup.layout(ViewGroup.java:6526)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23475)
       at android.view.ViewGroup.layout(ViewGroup.java:6526)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:23475)
       at android.view.ViewGroup.layout(ViewGroup.java:6526)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at
com.android.internal.policy.DecorView.onLayout(DecorView.java:1008)
       at android.view.View.layout(View.java:23475)
       at android.view.ViewGroup.layout(ViewGroup.java:6526)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3976)
       at
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3427)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2315)
       at
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9216)
       at
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1186)
       at android.view.Choreographer.doCallbacks(Choreographer.java:986)
       at android.view.Choreographer.doFrame(Choreographer.java:912)
       at
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1171)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8333)
       at java.lang.reflect.Method.invoke(Method.java)
       at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
