### ISSUE TITLE
setLifecycleOwner

### ISSUE THREAD

**Issue by Boscotec** [skydoves/PowerSpinner#9]
**Please complete the following information:**
- Library Version 1.0.3
- Affected Device(s) [TECNO Camon CX with 7.0, Samsung Galaxy Note 4]
 
**Describe the Bug:**
Fatal Exception: java.lang.IllegalArgumentException
The observer class has some methods that use newer APIs which are not available in the current OS version. Lifecycles cannot access even other methods so you should make sure that your observer classes only access framework classes that are available in your min API level OR use lifecycle:compiler annotation processor.

**Comment by Boscotec** [comment]
Caused by java.lang.ClassNotFoundException
Didn't find class "android.view.textclassifier.TextClassifier" on path: DexPathList[[zip file "/data/app/com.***.app-2/base.apk", zip file "/data/app/com.***.app-2/split_config.en.apk", zip file "/data/app/com.***.app-2/split_config.hdpi.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

**Comment by skydoves** [comment]
Hi, could you let me know your device's OS version?

**Comment by Boscotec** [comment]
Affected Device(s) 
  Brand: itel
  Model: it1556 Plus
  Version: 5.1

  Brand: TECNO
  Model: SPARK
  Version: 7.0
 
 Brand: samsung
 Model: Galaxy Note4
 Version: 5.1.1

those are the user devices.

**Comment by skydoves** [comment]
It seems like you need to add below dependency on your `gradle.build` file.
```gradle
annotationProcessor "androidx.lifecycle:lifecycle-compiler:2.2.0"
```
If you use kotlin,
```gradle
kapt "androidx.lifecycle:lifecycle-compiler:2.2.0"
```

**Comment by Boscotec** [comment]
It still crash on 
Brand: samsung
Model: Galaxy S10
Version: 7.1.2

after adding kapt "androidx.lifecycle:lifecycle-compiler:2.2.0"

**Comment by Boscotec** [comment]
Caused by java.lang.NoClassDefFoundError
android.view.textclassifier.TextClassifier

Caused by java.lang.ClassNotFoundException
Didn't find class "android.view.textclassifier.TextClassifier" on path: DexPathList[[zip file "/data/app/com.example.app.rc-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.app.rc-1/lib/x86_64, /system/lib64, /vendor/lib64, /data/downloads, /data/priv-downloads]]

**Comment by skydoves** [comment]
Hmm... It looks hard to find reasons from the log messages.
I think it is not compatible between the libraries `appcompat` version and yours.

```gradle
implementation(Libraries.balloon)  {
    exclude("androidx.appcompat", "appcompat")
}
```

or your project is not migrated to AndroidX yet?

**Comment by Boscotec** [comment]
The project is using AndroidX. TextClassifier was added in API level 26, so i can't setLifecycleOwner for devices with lower API level.

**Comment by mariooooo** [comment]
same problem
`java.lang.IllegalArgumentException: The observer class has some methods that use newer APIs which are not available in the current OS version. Lifecycles cannot access even other methods so you should make sure that your observer classes only access framework classes that are available in your min API level OR use lifecycle:compiler annotation processor.`
on device:
Brand: Meizu
Model: MX5
Version: 5.1

**Comment by skydoves** [comment]
It's released a new version `1.0.7`.
Please try using this version!

**Comment by Isma3ilMohamed** [comment]
Hey @skydoves 
I used version 1.0.8
but still have this issue 
```
 android.view.InflateException: Binary XML file line #374: Binary XML file line #374: Error inflating class com.skydoves.powerspinner.PowerSpinnerView
    Caused by: android.view.InflateException: Binary XML file line #374: Error inflating class com.skydoves.powerspinner.PowerSpinnerView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at com.baianat.app.base.BaseFragment.onCreateView(BaseFragment.kt:64)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.IllegalArgumentException: The observer class has some methods that use newer APIs which are not available in the current OS version. Lifecycles cannot access even other methods so you should make sure that your observer classes only access framework classes that are available in your min API level OR use lifecycle:compiler annotation processor.
        at androidx.lifecycle.ClassesInfoCache.getDeclaredMethods(ClassesInfoCache.java:72)
        at androidx.lifecycle.ClassesInfoCache.createInfo(ClassesInfoCache.java:122)
        at androidx.lifecycle.ClassesInfoCache.getInfo(ClassesInfoCache.java:85)
        at androidx.lifecycle.ClassesInfoCache.createInfo(ClassesInfoCache.java:108)
        at androidx.lifecycle.ClassesInfoCache.hasLifecycleMethods(ClassesInfoCache.java:60)
        at androidx.lifecycle.Lifecycling.resolveObserverCallbackType(Lifecycling.java:164)
        at androidx.lifecycle.Lifecycling.getObserverConstructorType(Lifecycling.java:146)
        at androidx.lifecycle.Lifecycling.lifecycleEventObserver(Lifecycling.java:83)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.<init>(LifecycleRegistry.java:347)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:174)
        at com.skydoves.powerspinner.PowerSpinnerView.setLifecycleOwner(PowerSpinnerView.kt:229)
        at com.skydoves.powerspinner.PowerSpinnerView.<init>(PowerSpinnerView.kt:247)
        	... 32 more
     Caused by: java.lang.NoClassDefFoundError: android.view.textclassifier.TextClassifier
        at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
        at java.lang.Class.getDexCacheType(Class.java:2551)
        at java.lang.reflect.Method.getReturnType(Method.java:150)
        at java.lang.Class.getDeclaredMethods(Class.java:1811)
        at androidx.lifecycle.ClassesInfoCache.getDeclaredMethods(ClassesInfoCache.java:70)
        	... 43 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.textclassifier.TextClassifier" on path: DexPathList[[zip file "/data/app/com.baianat.app.rigow-1/base.apk"],nativeLibraryDirectories=[/data/app/com.baianat.app.rigow-1/lib/x86, /data/app/com.baianat.app.rigow-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
        	... 47 more
        	```

**Comment by skydoves** [comment]
Hi @Isma3ilMohamed 
Please try to add the below dependency.

```gradle
Try to use kapt "androidx.lifecycle:lifecycle-compiler:2.0.0"
```

and set the viewLifecycler in your fragment.
```kotlin
powerSpinnerView.lifecycleOwner = viewLifecycle
```

**Comment by Isma3ilMohamed** [comment]
> Hi @Isma3ilMohamed
> Please try to add the below dependency.
> 
> ```groovy-gradle
> kapt "androidx.lifecycle:lifecycle-compiler:2.0.0"
> ```
> 
> and set the `viewLifecycleOwner` in your fragment.
> 
> ```kotlin
> powerSpinnerView.lifecycleOwner = viewLifecycleOwner
> ```
Hey @skydoves 
this issue still exists :(
what i've done
in build.gradle
```
    //spinner
    implementation "com.github.skydoves:powerspinner:1.1.8"
    kapt "androidx.lifecycle:lifecycle-compiler:2.0.0"
```

in BaseFragment
```
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        if (hideKeyboardWhenTouchOutside()) {
            keyboardDismissOnTouchOutside(view)
        }
        initLayout(savedInstanceState, view)


    }
    ```
    then in child fragment
   ```
       override fun initLayout(savedInstanceState: Bundle?, view: View) {
        citiesSpinner.lifecycleOwner=viewLifecycleOwner
        locationsSpinner.lifecycleOwner=viewLifecycleOwner

        presenter.attachView(this, lifecycle)
        .......
   ```
   in xml 
   ```
                       <com.skydoves.powerspinner.PowerSpinnerView
                        android:id="@+id/locationsSpinner"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginStart="20dp"
                        android:layout_marginTop="8dp"
                        android:layout_marginEnd="20dp"
                        android:background="@drawable/bg_spinner_white"
                        android:drawableTint="@color/black"
                        android:fontFamily="@font/font_regular"
                        android:hint="@string/branches"
                        android:maxLines="1"
                        android:padding="12dp"
                        android:textColor="@color/colorBlack"
                        android:textColorHint="@color/colorHint"
                        android:textSize="@dimen/fontLarge"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toBottomOf="@+id/locationTextView"
                        app:spinner_arrow_gravity="end"
                        app:spinner_arrow_padding="8dp"
                        app:spinner_arrow_show="true"
                        app:spinner_divider_show="true"
                        app:spinner_divider_size="0.4dp"
                        app:spinner_popup_animation="dropdown" />
                        
                                            <com.skydoves.powerspinner.PowerSpinnerView
                        android:id="@+id/citiesSpinner"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginStart="20dp"
                        android:layout_marginTop="8dp"
                        android:layout_marginEnd="20dp"
                        android:background="@drawable/bg_spinner_white"
                        android:drawableTint="@color/black"
                        android:fontFamily="@font/font_regular"
                        android:hint="@string/branches"
                        android:maxLines="1"
                        android:padding="12dp"
                        android:textColor="@color/colorBlack"
                        android:textColorHint="@color/colorHint"
                        android:textSize="@dimen/fontLarge"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toBottomOf="@+id/branchesTextView"
                        app:spinner_arrow_gravity="end"
                        app:spinner_arrow_padding="8dp"
                        app:spinner_arrow_show="true"
                        app:spinner_divider_show="true"
                        app:spinner_divider_size="0.4dp"
                        app:spinner_popup_animation="dropdown" />
   ```

   but i still have this issue


```
android.view.InflateException: Binary XML file line #374: Binary XML file line #374: Error inflating class com.skydoves.powerspinner.PowerSpinnerView
    Caused by: android.view.InflateException: Binary XML file line #374: Error inflating class com.skydoves.powerspinner.PowerSpinnerView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at com.baianat.app.base.BaseFragment.onCreateView(BaseFragment.kt:65)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.IllegalArgumentException: The observer class has some methods that use newer APIs which are not available in the current OS version. Lifecycles cannot access even other methods so you should make sure that your observer classes only access framework classes that are available in your min API level OR use lifecycle:compiler annotation processor.
        at androidx.lifecycle.ClassesInfoCache.getDeclaredMethods(ClassesInfoCache.java:72)
        at androidx.lifecycle.ClassesInfoCache.createInfo(ClassesInfoCache.java:122)
        at androidx.lifecycle.ClassesInfoCache.getInfo(ClassesInfoCache.java:85)
        at androidx.lifecycle.ClassesInfoCache.createInfo(ClassesInfoCache.java:108)
        at androidx.lifecycle.ClassesInfoCache.hasLifecycleMethods(ClassesInfoCache.java:60)
        at androidx.lifecycle.Lifecycling.resolveObserverCallbackType(Lifecycling.java:164)
        at androidx.lifecycle.Lifecycling.getObserverConstructorType(Lifecycling.java:146)
        at androidx.lifecycle.Lifecycling.lifecycleEventObserver(Lifecycling.java:83)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.<init>(LifecycleRegistry.java:347)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:174)
        at com.skydoves.powerspinner.PowerSpinnerView.setLifecycleOwner(PowerSpinnerView.kt:229)
        at com.skydoves.powerspinner.PowerSpinnerView.<init>(PowerSpinnerView.kt:247)
        	... 32 more
     Caused by: java.lang.NoClassDefFoundError: android.view.textclassifier.TextClassifier
        at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
        at java.lang.Class.getDexCacheType(Class.java:2551)
        at java.lang.reflect.Method.getReturnType(Method.java:150)
        at java.lang.Class.getDeclaredMethods(Class.java:1811)
        at androidx.lifecycle.ClassesInfoCache.getDeclaredMethods(ClassesInfoCache.java:70)
        	... 43 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.textclassifier.TextClassifier" on path: DexPathList[[zip file "/data/app/com.baianat.app.rigow-2/base.apk"],nativeLibraryDirectories=[/data/app/com.baianat.app.rigow-2/lib/x86, /data/app/com.baianat.app.rigow-2/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
        	... 47 more
```

i need to fix this one ASAP 
and thanks for all
